language: node_js
sudo: true
dist: trusty
node_js:
  - "6.0"
  - "8.0"
  - "10.0"
script: npm run test
notifications:
  email:
    on_failure: change
after_success: 'npm run coverage && npm run codeclimate'